/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PortfolioRouteImport } from "./routes/portfolio";
import { Route as PhotographyRouteImport } from "./routes/photography";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as BlogIndexRouteImport } from "./routes/blog.index";
import { Route as PortfolioSlugRouteImport } from "./routes/portfolio.$slug";
import { Route as BlogSlugRouteImport } from "./routes/blog.$slug";

const PortfolioRoute = PortfolioRouteImport.update({
  id: "/portfolio",
  path: "/portfolio",
  getParentRoute: () => rootRouteImport,
} as any);
const PhotographyRoute = PhotographyRouteImport.update({
  id: "/photography",
  path: "/photography",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => rootRouteImport,
} as any);
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => PortfolioRoute,
} as any);
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/blog/$slug",
  path: "/blog/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/photography": typeof PhotographyRoute;
  "/portfolio": typeof PortfolioRouteWithChildren;
  "/blog/$slug": typeof BlogSlugRoute;
  "/portfolio/$slug": typeof PortfolioSlugRoute;
  "/blog/": typeof BlogIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/photography": typeof PhotographyRoute;
  "/portfolio": typeof PortfolioRouteWithChildren;
  "/blog/$slug": typeof BlogSlugRoute;
  "/portfolio/$slug": typeof PortfolioSlugRoute;
  "/blog": typeof BlogIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/photography": typeof PhotographyRoute;
  "/portfolio": typeof PortfolioRouteWithChildren;
  "/blog/$slug": typeof BlogSlugRoute;
  "/portfolio/$slug": typeof PortfolioSlugRoute;
  "/blog/": typeof BlogIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/photography"
    | "/portfolio"
    | "/blog/$slug"
    | "/portfolio/$slug"
    | "/blog/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/photography"
    | "/portfolio"
    | "/blog/$slug"
    | "/portfolio/$slug"
    | "/blog";
  id:
    | "__root__"
    | "/"
    | "/photography"
    | "/portfolio"
    | "/blog/$slug"
    | "/portfolio/$slug"
    | "/blog/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PhotographyRoute: typeof PhotographyRoute;
  PortfolioRoute: typeof PortfolioRouteWithChildren;
  BlogSlugRoute: typeof BlogSlugRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/portfolio": {
      id: "/portfolio";
      path: "/portfolio";
      fullPath: "/portfolio";
      preLoaderRoute: typeof PortfolioRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/photography": {
      id: "/photography";
      path: "/photography";
      fullPath: "/photography";
      preLoaderRoute: typeof PhotographyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/": {
      id: "/blog/";
      path: "/blog";
      fullPath: "/blog/";
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/portfolio/$slug": {
      id: "/portfolio/$slug";
      path: "/$slug";
      fullPath: "/portfolio/$slug";
      preLoaderRoute: typeof PortfolioSlugRouteImport;
      parentRoute: typeof PortfolioRoute;
    };
    "/blog/$slug": {
      id: "/blog/$slug";
      path: "/blog/$slug";
      fullPath: "/blog/$slug";
      preLoaderRoute: typeof BlogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute;
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
};

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotographyRoute: PhotographyRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
